# Generated by Django 2.0.6 on 2018-06-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='user_id',
            field=models.UUIDField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
